### ISSUE TITLE
Supported Keras version and backend

### ISSUE THREAD

**Issue by Alteregoxxx** [bartkowiaktomasz/kerasify-lstm-arduino#3]
Does Headerify LSTM for C++ works with Keras 2, Keras 1 or both?
Which backend one have to use for the generation/training of the neural network, Tensorflow or Theano? 
Does the Keras model need to be sequential?

**Comment by bartkowiaktomasz** [comment]
For future refernce - supported Keras version was `~=2.2.0` (i.e. 2), not sure about Keras 1 (would need to check how weights are being stored in Keras 1). I believe the code is backend-agnostic as long as the structure of the (saved) model file isn't impacted. Yes the model needs to be Sequential.
