### ISSUE TITLE
How to feed continuous data from IMU to the model

### ISSUE THREAD

**Issue by yang12313** [bartkowiaktomasz/kerasify-lstm-arduino#4]
Hi,

I am wondering how you feed continuous IMU data into the model ? did you use buffer ?

**Comment by bartkowiaktomasz** [comment]
For future reference - in [this](https://github.com/bartkowiaktomasz/fitness-activity-classification-with-lstms) implementation the classification was performed in a local server based on data received from an IMU via Bluetooth Low Energy (i.e. not on a device directly).
